development:
  adapter: postgresql
  encoding: unicode
  database: college_timetable_development
  pool: 5
  username: sgnwow
  password: 2101
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: college_timetable_test
  pool: 5
  username: sgnwow
  password: 2101
  host: localhost
  port: 5432
